# Docker wrapper for a modified version of [fiche from pihole](https://github.com/pi-hole/tricorder) 
This is a docker container that runs a modified version of fiche in a container, and drops the input text into an html file in the nginx root. Each input text will have an autogenerated url when using `nc`
## Usage Example
```bash
ps auwwx | nc container-ip 59999
```
Will return a url like http://docker-host:10080/g89sfs.
## Network Ports
| Fiche Port | Docker Exposed Port |
| ---------- | ------------------- |
| 9999/tcp   | 59999/tcp           |
| 80/tcp     | 10080/tcp           |

These can be modified in the Dockerfile, the line where it echos the fiche command to the run_nginx.sh file.
